---
- name: configure passwordless ssh authentication on a remote machine
  hosts: localhost

  roles:
    - role: ryankwilliams.ssh_copy_id
      vars:
        hostname: 127.0.0.1
        username: username
        password: password
        ssh_public_key: /home/username/.ssh/id_rsa.pub
        ssh_port: 22
